name: Healthcheck

on:
  schedule:
    - cron: '53 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: check that the app is running
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fsdex.herokuapp.com/
          max-attempts: 3 
          retry-delay: 5s