
name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test join
        env:
          GITHUB_CONTEXT: ${{ join(github.event.commits.*.message) }}
        run: echo "$GITHUB_CONTEXT"
      - name: test contains - true
        env:
          COMMITS: ${{ contains(join(github.event.commits.*.message, 'testing')) }}
        run: echo "$COMMITS"
      - name: test contains - false
        env:
          COMMIT_MESSAGES: ${{ contains(join(github.event.commits.*.message, 'cat')) }}
        run: echo "$COMMIT_MESSAGES"